# This script creates a simple LLM workflow using LangGraph. It defines a state graph with nodes and edges, compiles the graph into an executable workflow, and then executes the workflow with some input data/state. 
# The workflow takes a question as input, uses the LLM to generate an answer, and returns the answer as output.

from langgraph.graph import StateGraph, START, END
from langchain_openai import ChatOpenAI
from typing import TypedDict
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Create an instance of the ChatOpenAI model. This will be used as the language model for our workflow to process the input and generate responses.
llm = ChatOpenAI()

# Define State of the Graph
class LLM_State(TypedDict):
    question: str  # The question to be answered by the LLM
    answer: str    # The answer generated by the LLM

# Define a function to generate an answer using the LLM
def generate_answer(state: LLM_State) -> LLM_State:
    """
    Generate an answer to the question using the LLM.
    """
    question = state['question']
    prompt = f"Answer the following question: {question}"
    answer = llm.invoke(prompt)
    state['answer'] = answer.content
    return state

# Define a graph
graph = StateGraph(LLM_State)

# Add nodes to the graph
graph.add_node("Generate_Answer", generate_answer)

# Add edges to the nodes to create a graph workflow.
graph.add_edge(START, "Generate_Answer")
graph.add_edge("Generate_Answer", END)

# Compile the graph to create an executable workflow
compiled_workflow = graph.compile()

# Execute the workflow with some input data/state
input_state = {
    'question': "What is the distance between the Earth and Jupiter?"
}

final_state = compiled_workflow.invoke(input_state)
print(final_state)
