# Vector Store Retriever is a component in LangChain that allows you to retrieve relevant documents from a vector store based on a query. 
# It uses the embeddings generated by the embedding model to find similar documents in the vector store. 
# This can be useful for various applications, such as question-answering, information retrieval, and content recommendation.

from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.documents import Document

from dotenv import load_dotenv

load_dotenv()

# Create an instance of the OpenAIEmbeddings class to generate vector embeddings for our documents. 
# We will use the "text-embedding-3-small" model to generate 384-dimensional embeddings for our text data.
embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")

documents = [
     Document(
        page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.",
        metadata={"team": "Royal Challengers Bangalore"}
    ),
    Document(
        page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.",
        metadata={"team": "Mumbai Indians"}
    ),
    Document(
        page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.",
        metadata={"team": "Chennai Super Kings"}
    ),
    Document(
        page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.",
        metadata={"team": "Mumbai Indians"}
    ),
    Document(
        page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.",
        metadata={"team": "Chennai Super Kings"}
    )   
]

# Create an instance of the Chroma vector store. We will specify the collection name as "my_collection" and the embedding model we created earlier.

vector_store = Chroma.from_documents(
    documents=documents,  # List of documents to add to the vector store
    embedding=embedding_model,  # Function to generate embeddings for queries
    collection_name="my_collection",
)    

# Search for similar documents in the vector store using a query.
# as_retriever method converts the vector store into a retriever that can be used to retrieve relevant documents based on a query. 
# The search method takes a query string and returns a list of relevant documents from the vector store.

retriever = vector_store.as_retriever(search_kwargs={"k": 2})  # Set the number of top results to retrieve

query = "Who is the best captain in IPL history?"

relevant_docs = retriever.invoke(query)

for i, doc in enumerate(relevant_docs):    
    print(f"Relevant document {i+1}:\n", doc.page_content)
    print("Metadata:", doc.metadata)
    print("\n")