from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableSequence, RunnableParallel, RunnablePassthrough, RunnableLambda

load_dotenv()

model = ChatOpenAI(model="gpt-4o-mini", temperature=0.7)

parser = StrOutputParser()

prompt = PromptTemplate(
    template="Write a joke about {topic}.",
    input_variables=["topic"]
)

report = prompt | model | parser

# Runnable Lambda is used to create a runnable from a lambda function. This is useful when we want to create a runnable from a simple function that does not require any complex logic. We can also use the same runnable in different chains without needing to create new instances of them.

# In this case, we are going to count the words in a report on a specific topic.

def word_count(text):
    return len(text.split())

# Created a Runnable using the python function word_count.
# We can now use this runnable in our chain to count the words in the report generated by the first runnable. And print the report as well using Runnable Passthrough.

para_chain = RunnableParallel({
    'joke': RunnablePassthrough(),
    'word_count': RunnableLambda(word_count)    
})

final_chain = report | para_chain

result = final_chain.invoke({"topic": "West Bengal Elections"})

print("Full Output:\n", result)