from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableSequence, RunnableParallel, RunnablePassthrough

load_dotenv()

model = ChatOpenAI(model="gpt-4o-mini", temperature=0.7)

parser = StrOutputParser()

# prompt = PromptTemplate(
#     template="Generate interesting facts about {topic}. Keep the response under 500 words",
#     input_variables=["topic"]
# )

prompt = PromptTemplate(
    template="Tell me a joke about {topic}.",
    input_variables=["topic"]
)

#  This is the chain where model and parser are already used. So we can directly use them without needing to create a new chain for this.
prompt2 = PromptTemplate(                       #
    template="Explain the joke {joke}",
    input_variables=['joke']
) | model | parser


joke = prompt | model | parser

# Runnable Passthrough is used to pass the output of one runnable to another runnable without any modification. This is useful when we want to use the output of one runnable as the input of another runnable without needing to create a new chain for this. We can also use the same runnable in different chains without needing to create new instances of them.
# In this case, we want to pass the joke generated by the first runnable to the second runnable without any modification. So we can use RunnablePassthrough for this.

explanation = RunnableParallel({ 
    'joke': RunnablePassthrough(),
    'explanation': prompt2
})

seq_chain = joke | explanation

result = seq_chain.invoke({"topic": "AI in general"})

print("Full Output:", result)

print("Joke:", result['joke'])
print("Explanation:", result['explanation'])
